'use client';
import { useEffect, useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, Check, MessageCircle, Upload, X, CalendarDays, ShieldCheck, Phone } from 'lucide-react';
import { areas, wa, PHONE } from '@/lib/site-data';
const categories=['Engine','Electrical','Battery','Starter','Alternator','Brakes','Suspension','Steering','Overheating','Vehicle Not Starting','Warning Light','Maintenance','Other'];
const steps=['Your details','Your vehicle','The problem','Location & time','Review'];
type Details={name:string;phone:string;whatsapp:string;make:string;model:string;year:string;registration:string;category:string;description:string;service:string;area:string;address:string;map:string;date:string;time:string};
const initial:Details={name:'',phone:'',whatsapp:'',make:'',model:'',year:'',registration:'',category:'',description:'',service:'Mobile Mechanic',area:'',address:'',map:'',date:'',time:'Flexible'};
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function bookingMessage(d:Details){return `Hi Niaz Autos, I’d like to request a booking.\n\nCUSTOMER\nName: ${d.name.trim()}\nPhone: ${d.phone.trim()}\nWhatsApp: ${d.whatsapp.trim()}\n\nVEHICLE\n${d.make.trim()} ${d.model.trim()} (${d.year})${d.registration.trim()?`\nRegistration: ${d.registration.trim()}`:''}\n\nPROBLEM\nCategory: ${d.category}\n${d.description.trim()}\n\nSERVICE\n${d.service}\n\nLOCATION\n${d.service==='Visit Workshop'?'Niaz Autos, Township, Lahore':`${d.area||'To be confirmed'}\n${d.address||'To be shared'}${d.map?`\nMaps: ${d.map}`:''}`}\n\nPREFERRED TIME\n${d.date} — ${d.time}\n\nPlease confirm availability and applicable charges. I understand that a free eligible visit covers travel only; inspection, labor, service and parts may be charged.`;}
export default function Booking(){
 const [data,setData]=useState<Details>(initial);const [step,setStep]=useState(0);const [error,setError]=useState('');const [photos,setPhotos]=useState<{name:string;url:string}[]>([]);const [opened,setOpened]=useState(false);const form=useRef<HTMLFormElement>(null);const title=useRef<HTMLHeadingElement>(null);const photoRef=useRef(photos);photoRef.current=photos;
 const update=(key:keyof Details,value:string)=>setData(d=>({...d,[key]:value}));
 useEffect(()=>()=>photoRef.current.forEach(p=>URL.revokeObjectURL(p.url)),[]);
 useEffect(()=>{const prefill=(e:Event)=>{const c=(e as CustomEvent<string>).detail;if(categories.includes(c)){setData(d=>({...d,category:c}));setStep(0);setOpened(false)}};window.addEventListener('niaz:service',prefill);return()=>window.removeEventListener('niaz:service',prefill)},[]);
 const move=(n:number)=>{setStep(n);setError('');requestAnimationFrame(()=>title.current?.focus({preventScroll:true}));};
 const validate=()=>{if(!form.current?.reportValidity())return false;if(step===0){for(const key of ['phone','whatsapp'] as const){const digits=data[key].replace(/\D/g,'');if(digits.length<10||digits.length>15){setError('Please enter a valid phone and WhatsApp number with 10–15 digits.');return false}}if(!data.name.trim()){setError('Please enter your full name.');return false}}if(step===1&&(!data.make.trim()||!data.model.trim())){setError('Please enter your vehicle make and model.');return false}if(step===2&&data.description.trim().length<10){setError('Please describe the issue in at least 10 characters.');return false}if(step===3){if(data.date<today()){setError('Please choose today or a future date.');return false}if(data.service==='Mobile Mechanic'&&!data.address.trim()){setError('Please add your full address or a landmark.');return false}if(data.map){try{const url=new URL(data.map);if(url.protocol!=='https:'||!['maps.app.goo.gl','maps.google.com','goo.gl','www.google.com','google.com'].includes(url.hostname)){setError('Please use an HTTPS Google Maps location link.');return false}}catch{setError('Please enter a valid Google Maps link.');return false}}}return true;};
 const next=(e:FormEvent)=>{e.preventDefault();if(validate())move(Math.min(step+1,4));};
 const input=(key:keyof Details,label:string,opts:{type?:string;optional?:boolean;placeholder?:string;maxLength?:number;autoComplete?:string}={})=><label className="field"><span>{label}{opts.optional&&<em>Optional</em>}</span><input name={key} value={data[key]} onChange={e=>update(key,e.target.value)} type={opts.type||'text'} required={!opts.optional} placeholder={opts.placeholder} autoComplete={opts.autoComplete||'off'} maxLength={opts.maxLength||100}/></label>;
 const addPhotos=(e:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(e.target.files||[]);e.target.value='';if(files.length+photos.length>4){setError('Please select up to 4 photos.');return}if(files.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>8*1024*1024)){setError('Use JPG, PNG or WebP photos, up to 8 MB each.');return}setError('');setPhotos(p=>[...p,...files.map(f=>({name:f.name,url:URL.createObjectURL(f)}))]);};
 return <div className="booking-card"><div className="booking-progress" aria-label="Booking progress">{steps.map((s,i)=><div key={s} className={`${i===step?'current':''} ${i<step?'complete':''}`} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><small>{s}</small></div>)}</div><form ref={form} onSubmit={next}><div className="form-heading"><span className="eyebrow">STEP {String(step+1).padStart(2,'0')} / 05</span><h3 ref={title} tabIndex={-1}>{['Let’s get to know you.','Tell us what you drive.','What needs our attention?','Where and when?','Ready when you are.'][step]}</h3><p>{['A few details so our team can get back to you.','Help us prepare for your vehicle.','The more we know, the better we can help.','We’ll confirm availability before your visit.','Check your request, then send it to our team on WhatsApp.'][step]}</p></div>
 {step===0&&<div className="form-grid">{input('name','Full name',{placeholder:'Your full name',autoComplete:'name'})}{input('phone','Phone number',{type:'tel',placeholder:'0304 1234567',autoComplete:'tel',maxLength:22})}{input('whatsapp','WhatsApp number',{type:'tel',placeholder:'+92 304 1234567',maxLength:22})}<div className="form-note"><ShieldCheck size={20}/><p>Your details are used to prepare your WhatsApp message. They aren’t saved on this website.</p></div></div>}
 {step===1&&<div className="form-grid">{input('make','Vehicle make',{placeholder:'e.g. Toyota'})}{input('model','Vehicle model',{placeholder:'e.g. Corolla'})}<label className="field"><span>Year</span><input name="year" type="number" inputMode="numeric" required min="1950" max={new Date().getFullYear()+1} value={data.year} onChange={e=>update('year',e.target.value)} placeholder="e.g. 2020"/></label>{input('registration','Registration number',{optional:true,placeholder:'e.g. LEA 1234',maxLength:25})}</div>}
 {step===2&&<><label className="field"><span>Problem category</span><select name="category" required value={data.category} onChange={e=>update('category',e.target.value)}><option value="">Choose a category</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="field"><span>Describe the problem</span><textarea name="description" required minLength={10} maxLength={1200} rows={4} value={data.description} onChange={e=>update('description',e.target.value)} placeholder="What’s happening? When did it start? Any warning lights or unusual sounds?"/></label><fieldset className="service-choices"><legend>How would you like us to help?</legend>{['Mobile Mechanic','Visit Workshop','Not Sure'].map(s=><label key={s} className={data.service===s?'selected':''}><input type="radio" name="service" value={s} checked={data.service===s} onChange={()=>update('service',s)}/>{s}</label>)}</fieldset><div className="upload-area"><label className="upload-trigger"><Upload size={19}/><span>Add vehicle / problem photos <small>Optional · Up to 4 photos · JPG, PNG, WebP · 8 MB each</small></span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={addPhotos}/></label><p>Photos stay on your device. Attach them directly in WhatsApp after your message opens.</p>{photos.length>0&&<div className="photo-previews">{photos.map((p,i)=><div key={p.url}><img src={p.url} alt={p.name}/><button type="button" aria-label={`Remove ${p.name}`} onClick={()=>{URL.revokeObjectURL(p.url);setPhotos(ps=>ps.filter((_,n)=>n!==i))}}><X size={14}/></button><small>{p.name}</small></div>)}</div>}</div></>}
 {step===3&&<><div className="form-grid">{data.service!=='Visit Workshop'&&<><label className="field"><span>Area {data.service==='Not Sure'&&<em>Optional</em>}</span><select name="area" required={data.service==='Mobile Mechanic'} value={data.area} onChange={e=>update('area',e.target.value)}><option value="">Select your area</option>{areas.map(a=><option key={a}>{a}</option>)}<option>Other area</option></select></label>{input('address','Full address / landmark',{optional:data.service!=='Mobile Mechanic',placeholder:'Street, building and nearest landmark',maxLength:250})}<div className="full-width">{input('map','Google Maps location link',{optional:true,type:'url',placeholder:'https://maps.app.goo.gl/…',maxLength:500})}</div></>}{data.service==='Visit Workshop'&&<div className="form-note full-width"><WrenchSymbol/><p>Your request is for <strong>Niaz Autos, Township, Lahore.</strong> Our team will confirm the workshop visit with you.</p></div>}<label className="field"><span>Preferred date</span><input name="date" type="date" required min={today()} value={data.date} onChange={e=>update('date',e.target.value)}/></label><label className="field"><span>Preferred time</span><select name="time" value={data.time} onChange={e=>update('time',e.target.value)}>{['Morning','Afternoon','Evening','Flexible'].map(t=><option key={t}>{t}</option>)}</select></label></div><p className="form-disclaimer"><CalendarDays size={16}/> Requested time is subject to confirmation.</p>{data.service==='Mobile Mechanic'&&<p className="form-disclaimer">Free mobile mechanic visit is available in selected nearby areas and subject to availability. Inspection, repair, labor and parts are chargeable.</p>}</>}
 {step===4&&<div className="booking-summary"><dl>{[['Customer',`${data.name} · ${data.phone}`],['WhatsApp',data.whatsapp],['Vehicle',`${data.make} ${data.model} · ${data.year}${data.registration?` · ${data.registration}`:''}`],['Problem',`${data.category}: ${data.description}`],['Service',data.service],['Location',data.service==='Visit Workshop'?'Niaz Autos, Township, Lahore':`${data.area||'To be confirmed'}${data.address?` · ${data.address}`:''}`],...(data.map&&data.service!=='Visit Workshop'?[['Maps',data.map]]:[]),['Preferred time',`${data.date} · ${data.time}`]].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><div className="summary-note"><Check size={18}/><p>No travel / visit fee in selected nearby areas. <strong>The repair itself is not free.</strong> Inspection, labor, service and parts charges may apply.</p></div><p className="form-disclaimer">Requested time is subject to confirmation. Your booking is a request until our team confirms it.</p>{photos.length>0&&<p className="photo-reminder">{photos.length} photo{photos.length>1?'s':''} selected. After WhatsApp opens, please attach your vehicle/problem photos directly in the chat.</p>}</div>}
 {error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions">{step>0&&<button type="button" className="back-button" onClick={()=>move(step-1)}><ArrowLeft size={16}/> Back</button>}{step<4?<button type="submit" className="button">{step===3?'REVIEW BOOKING':'CONTINUE'}<ArrowRight size={17}/></button>:<a className="button whatsapp-send" href={wa(bookingMessage(data))} target="_blank" rel="noopener noreferrer" onClick={e=>{if(data.date<today()){e.preventDefault();move(3);setError('Please update your preferred date.');return}setOpened(true)}}><MessageCircle size={18}/> SEND BOOKING ON WHATSAPP</a>}</div>{opened&&<div className="handoff-note" role="status">Your WhatsApp message is ready. Please press Send in WhatsApp to submit your request. Need another way to reach us? <a href={PHONE}>Call +92 304 7952115.</a></div>}</form></div>;
}
function WrenchSymbol(){return <Phone size={22}/>}
