'use client';
import { useEffect, useState, useRef } from 'react';
import dynamic from 'next/dynamic';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, ArrowDown, Phone, MessageCircle, MapPin, Menu, X, Wrench, ShieldCheck, Truck, Check, ArrowRight, BatteryCharging, Cog, Gauge, Disc3, Zap, Navigation, Plus, CircleCheck, Settings2 } from 'lucide-react';
import { PHONE, MAPS, wa, areas, services, problems, faqs } from '@/lib/site-data';
import Booking from './booking';
const Scene=dynamic(()=>import('./scene'),{ssr:false,loading:()=> <div className="stage-loading"><span className="loading-ring"/> PREPARING YOUR 3D EXPERIENCE</div>});
const nav = [['Home','home'],['Services','services'],['Mechanic on Wheels','mobile-mechanic'],['Service Areas','areas'],['Booking','booking'],['Contact','contact']];
export function Brand() { return <a className="brand" href="#home" aria-label="Niaz Autos home"><span className="brand-mark">NA<span /></span><span>NIAZ<span className="brand-light"> AUTOS</span><small>PRECISION. CARE. EVERYWHERE.</small></span></a>; }
const icons=[Wrench,Settings2,Cog,Zap,BatteryCharging,Disc3,Gauge,Gauge,ShieldCheck,Truck];
function External({href,children,className=''}:{href:string;children:React.ReactNode;className?:string}){return <a href={href} target="_blank" rel="noopener noreferrer" className={className}>{children}</a>}
function requestService(category:string){window.dispatchEvent(new CustomEvent('niaz:service',{detail:category}));document.getElementById('booking')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
export default function HomePage() {
 const [menu,setMenu]=useState(false);const [scrolled,setScrolled]=useState(false);const [service,setService]=useState(2);const menuButton=useRef<HTMLButtonElement>(null);const reduced=useReducedMotion();
 useEffect(()=>{const run=()=>setScrolled(window.scrollY>30);run();window.addEventListener('scroll',run,{passive:true});return()=>window.removeEventListener('scroll',run);},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&menu){setMenu(false);menuButton.current?.focus()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[menu]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{context.registerTool({name:'start_mechanic_booking',title:'Start a Niaz Autos booking request',description:'Scroll to the booking form and optionally select a problem category. Does not send a request or confirm an appointment.',inputSchema:{type:'object',properties:{category:{type:'string',enum:[...new Set(services.map(s=>s.category))]}},additionalProperties:false},execute:async(input:unknown)=>{const value=input as {category?:string};if(!value||typeof value!=='object'||Object.keys(value).some(k=>k!=='category')||(value.category&&!services.some(s=>s.category===value.category)))throw new Error('Invalid problem category');requestService(value.category||'Other');await new Promise<void>(r=>requestAnimationFrame(()=>r()));return {status:'booking_form_open',requestSent:false};}},{signal:life.signal})}catch{/* Optional browser capability. */}return()=>life.abort()},[]);
 const localBusiness={'@context':'https://schema.org','@type':'AutoRepair',name:'Niaz Autos',description:'Complete vehicle repair and maintenance at our Township workshop and mobile mechanic service in selected nearby Lahore areas.',telephone:'+923047952115',address:{'@type':'PostalAddress',addressLocality:'Township, Lahore',addressRegion:'Punjab',addressCountry:'PK'},areaServed:areas.map(name=>({'@type':'Place',name})),hasMap:MAPS};
 const faqSchema={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))};
 return <><a className="skip-link" href="#main">Skip to content</a><header className={`nav ${scrolled?'scrolled':''}`}><div className="nav-inner"><Brand/><nav id="main-navigation" aria-label="Main navigation" className={menu?'nav-links open':'nav-links'}>{nav.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</nav><a className="button small nav-book" href="#booking">BOOK A MECHANIC <ArrowUpRight size={16}/></a><button ref={menuButton} className="menu-button" aria-label={menu?'Close navigation':'Open navigation'} aria-controls="main-navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main id="main"><section className="hero" id="home"><div className="hero-lines"/><figure className="hero-workshop"><img src="/images/niaz-autos-workshop.png" width={1536} height={1024} alt="Niaz Autos workshop in Township, Lahore" fetchPriority="high" decoding="async"/></figure><div className="hero-content shell"><div className="eyebrow"><span className="tiny-line"/> YOUR CAR. OUR COMMITMENT.</div><h1>COMPLETE<br/>AUTO CARE.<br/><span>ANYWHERE</span><br/><span>YOU NEED IT.</span></h1><p className="hero-description">From engine repairs and electrical diagnostics to complete mechanical maintenance. At our workshop. Or at your doorstep.</p><div className="hero-actions"><a className="button" href="#booking">BOOK MOBILE MECHANIC <ArrowUpRight size={19}/></a><a className="text-link" href={PHONE}><Phone size={15}/> CALL +92 304 7952115</a></div><External className="hero-whatsapp" href={wa()}><MessageCircle size={16}/> WHATSAPP US <ArrowUpRight size={14}/></External></div><div className="hero-bottom shell"><a href="#mobile-mechanic" className="visit-offer"><span className="offer-icon"><Truck size={23}/></span><span><strong>FREE MECHANIC VISIT IN SELECTED NEARBY AREAS*</strong><small>*No travel/visit fee. Inspection, labor and parts charges may apply.</small></span><ArrowUpRight size={20}/></a><a className="scroll-link" href="#services">EXPLORE OUR SERVICES <ArrowDown size={16}/></a></div></section>
 <div className="trust-strip"><span><Wrench size={17}/> COMPLETE AUTO REPAIR</span><span><ShieldCheck size={17}/> MECHANICAL + ELECTRICAL</span><span><Truck size={17}/> WORKSHOP + DOORSTEP</span><span><MapPin size={17}/> TOWNSHIP, LAHORE</span></div>
 <section className="section shell" id="services"><div className="section-heading"><div><div className="eyebrow">01 / EXPERTISE THAT GOES FURTHER</div><h2>EVERY SYSTEM.<br/><span>ONE WORKSHOP.</span></h2></div><p className="section-copy">From the engine under your hood to the electronics behind your dashboard. Complete care, all in one place.</p></div><div className="service-explorer"><div className="service-list" aria-label="Explore repair services">{services.map((s,i)=>{const Icon=icons[i];return <button key={s.name} className={`service-card ${service===i?'selected':''}`} aria-pressed={service===i} onClick={()=>setService(i)}><Icon size={21}/><span>{s.name}</span><ArrowUpRight size={17}/></button>})}</div><div className="service-feature"><span className="technical-label">NIAZ AUTOS / SYSTEM {String(service+1).padStart(2,'0')}</span><div className="component-stage"><Scene variant="part" part={services[service].type}/></div><div className="feature-content" aria-live="polite"><span className="eyebrow">PRECISION IN EVERY REPAIR</span><h3>{services[service].name}</h3><p>{services[service].description}</p><button className="text-link accent-link" onClick={()=>requestService(services[service].category)}>BOOK THIS SERVICE <ArrowUpRight size={17}/></button></div><span className="feature-cross top">+</span><span className="feature-cross bottom">+</span></div></div></section>
 <section className="mobile-section" id="mobile-mechanic"><div className="shell mobile-grid"><div className="mobile-copy"><div className="eyebrow">02 / MECHANIC ON WHEELS</div><h2>THE WORKSHOP<br/><span>COMES TO YOU.</span></h2><p>Stuck at home? Trouble on the road? You don’t always need to bring your car to us. Tell us what’s wrong, share your location, and we’ll confirm a mechanic’s visit.</p><div className="free-offer"><div><span className="free-word">FREE</span><strong>TRAVEL / VISIT<span>IN SELECTED NEARBY AREAS</span></strong></div><p>You pay only applicable:</p><ul>{['Inspection / diagnostics','Repair work','Labor / mechanic service','Required parts'].map(t=><li key={t}><Check size={15}/>{t}</li>)}</ul><small>The repair itself is not free. Free mobile mechanic visit is available in selected nearby areas and subject to availability.</small></div><div className="button-row"><a className="button" href="#booking">REQUEST MOBILE MECHANIC <ArrowUpRight size={17}/></a><a className="text-link" href={PHONE}><Phone size={16}/> CALL NOW</a></div></div><div className="mobile-visual"><div className="road-word" aria-hidden="true">ON<br/>WHEELS.</div><Scene variant="road"/><div className="location-chip"><Navigation size={18}/><span>FROM TOWNSHIP.<strong>TO YOUR LOCATION.</strong></span></div></div></div></section>
 <section className="section shell process-section"><div className="section-heading"><div><div className="eyebrow">A SIMPLE WAY TO GET MOVING AGAIN</div><h2>FOUR STEPS.<br/><span>LESS DOWNTIME.</span></h2></div><p className="section-copy">A conversation is all it takes to start.<br/>We’ll help you with the next step.</p></div><div className="process-grid">{[['Tell Us the Problem','Call or WhatsApp and explain the vehicle issue.',Phone],['Share Your Location','Send your location and vehicle details.',MapPin],['Mechanic Comes to You','Our mechanic travels to eligible nearby areas without a visit fee, subject to availability.',Truck],['Inspection & Repair','We inspect the vehicle, explain the issue and carry out the agreed service.',Wrench]].map(([name,desc,Icon],i)=>{const StepIcon=Icon as typeof Phone;return <motion.div className="process-card" key={String(name)} initial={reduced?false:{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.45,delay:i*.1}}><div className="process-top"><span>0{i+1}</span><StepIcon size={24}/></div><h3>{String(name)}</h3><p>{String(desc)}</p></motion.div>})}</div></section>
 <section className="areas-section" id="areas"><div className="shell areas-grid"><div><div className="eyebrow">03 / LOCAL ROADS. LOCAL EXPERTISE.</div><h2>WE COME<br/><span>TO YOU.</span></h2><p className="section-copy">Based in Township. Reaching your neighborhood.<br/>Selected nearby areas qualify for a mechanic visit with no travel / visit fee.</p><div className="area-tags">{areas.map(a=><span key={a}><MapPin size={14}/>{a}</span>)}</div><External className="button" href={wa('Hi Niaz Autos, I want to check if mobile mechanic service is available in my area. My location is:')}>CHECK YOUR LOCATION <ArrowUpRight size={18}/></External><p className="small-print">Free mobile mechanic visit is available in selected nearby areas and subject to availability.</p></div><div className="coverage-visual" aria-label="Illustrative service coverage around Township in Lahore"><div className="coverage-ring ring-one"/><div className="coverage-ring ring-two"/><div className="coverage-ring ring-three"/><div className="coverage-center"><span className="brand-mark">NA</span><strong>TOWNSHIP</strong><small>OUR WORKSHOP</small></div><span className="coverage-label label-one">MODEL TOWN</span><span className="coverage-label label-two">JOHAR TOWN</span><span className="coverage-label label-three">FAISAL TOWN</span><span className="coverage-label label-four">WAPDA TOWN</span><span className="coverage-caption">LAHORE, PAKISTAN · ILLUSTRATIVE COVERAGE</span></div></div></section>
 <section className="section shell problems-section"><div className="eyebrow">SOMETHING DOESN’T FEEL RIGHT?</div><h2>CAR TROUBLE?<br/><span>CALL NIAZ AUTOS.</span></h2><div className="problem-tags">{problems.map(p=><External key={p} href={wa(`Hi Niaz Autos, I need help with my vehicle. The problem is: ${p}.`)}>{p}<ArrowUpRight size={14}/></External>)}</div><External className="text-link accent-link" href={wa('Hi Niaz Autos, I’d like to tell you about my vehicle problem:')}>TELL US YOUR VEHICLE PROBLEM <ArrowRight size={18}/></External></section>
 <section className="section shell booking-section" id="booking"><div className="booking-intro"><div className="eyebrow">05 / LET’S GET YOU BACK ON THE ROAD</div><h2>YOUR NEXT<br/>MOVE.<br/><span>OUR EXPERTISE.</span></h2><p className="section-copy">Tell us about your car and the help you need. Review your request, then send it directly to Niaz Autos on WhatsApp.</p><div className="booking-benefits"><span><CircleCheck size={18}/> Workshop or mobile service</span><span><CircleCheck size={18}/> No online payment required</span><span><CircleCheck size={18}/> Confirm the details with our team</span></div><div className="booking-help"><small>PREFER TO TALK?</small><a href={PHONE}>+92 304 7952115 <ArrowUpRight size={19}/></a></div></div><Booking/></section>
 <section className="location-section" id="contact"><div className="shell location-grid"><div><div className="eyebrow">YOUR LOCAL WORKSHOP</div><h2>VISIT<br/><span>NIAZ AUTOS.</span></h2><p><MapPin size={18}/> Township, Lahore, Pakistan</p><a className="location-phone" href={PHONE}>+92 304 7952115 <ArrowUpRight size={20}/></a><p className="small-print">Call ahead to confirm workshop availability.</p><External className="button" href={MAPS}>OPEN IN GOOGLE MAPS <ArrowUpRight size={18}/></External></div><div className="location-panel"><div className="location-panel-top"><MapPin size={34}/><span>LAHORE<br/><strong>TOWNSHIP</strong></span></div><div className="location-rule"/><p>One workshop.<br/><span>Complete vehicle care.</span></p><div className="location-panel-bottom"><span>NIAZ AUTOS</span><External href={MAPS}>GET DIRECTIONS <ArrowUpRight size={18}/></External></div></div></div></section>
 <section className="section shell faq-section"><div><div className="eyebrow">A FEW THINGS TO KNOW</div><h2>YOUR QUESTIONS.<br/><span>CLEAR ANSWERS.</span></h2><p className="section-copy">Need something else?<br/><External className="accent-link" href={wa()}>Ask us on WhatsApp <ArrowUpRight size={16}/></External></p></div><div className="faq-list">{faqs.map(([q,a],i)=><details key={q}><summary><span className="faq-number">{String(i+1).padStart(2,'0')}</span><span>{q}</span><Plus size={18}/></summary><p>{a}</p></details>)}</div></section>
 </main><footer><div className="shell footer-main"><div><Brand/><p>Complete Auto Repair & Maintenance<br/>Township, Lahore, Pakistan</p><a href={PHONE}>+92 304 7952115</a></div><div className="footer-links">{nav.slice(1).map(([name,id])=><a href={`#${id}`} key={id}>{name}</a>)}<External href={MAPS}>Google Maps <ArrowUpRight size={13}/></External></div><div className="footer-message"><span>KEEPING LAHORE</span><strong>MOVING.</strong></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Niaz Autos. All rights reserved.</span><span>WORKSHOP EXPERTISE. DOORSTEP CONVENIENCE.</span></div></footer><External className="floating-wa" href={wa()}><span className="sr-only">Chat on WhatsApp</span><MessageCircle/></External><div className="mobile-bar"><a href={PHONE}><Phone size={18}/>CALL</a><External href={wa()}><MessageCircle size={18}/>WHATSAPP</External><a href="#booking"><Wrench size={18}/>BOOK MECHANIC</a></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(localBusiness).replace(/</g,'\\u003c')}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema).replace(/</g,'\\u003c')}}/></>;
}
